### ISSUE TITLE
question: is this missing a case for the schema's `number` type? 

### ISSUE THREAD

**Issue by nilslice** [dylibso/xtp-typescript-bindgen#4]
https://github.com/dylibso/xtp-typescript-bindgen/blob/0073c97610710d8ef762f3934b0747dc1be1cb75/src/index.ts#L16

From the docs: 
```
ValueProperty ...
type (string, required): Must be one of: ["integer", "string", "number", "boolean", "object", "array", "buffer"].
...
```

**Comment by bhelx** [comment]
i'll follow up with this fix tomorrow

**Comment by nilslice** [comment]
Awesome - will follow your lead on the type usage. Also, it might be a good spot to add the switch for the format specifiers here too...
